import { StyleSheet } from "react-native";
import { colors } from "../../../styles/GlobalStyles";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.white,
        /* alignItems: "center", */
        /* justifyContent: "center", */
        /* marginTop: 100, */
    },
    avatar: {
		position: 'absolute',
		zIndex: 1,
		top: -60,
		height: 120,
		width: 120,
		alignSelf: 'center',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		borderWidth: 1,
		borderColor: 'transparent',
		backgroundColor: colors.text_gray,
		borderRadius: 16,
	},
	buttonAvatar: {
		zIndex: 2,
		top: -14,
		right: -13,
		transform: [{ rotate: '45deg' }],
		height: 25,
		width: 25,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 25,
		borderWidth: 1,
		borderColor: colors.orange,
		backgroundColor: colors.white,
	},
	buttonAvatarText: {
		color: colors.orange,
		fontSize: 16,
    },
    avatarContainer: {
		position: 'relative',
		alignSelf: 'center',
		justifyContent: 'center',
	},
	image: {
		position: 'absolute',
		zIndex: 1,
		top: -60,
		height: 120,
		width: 120,
		alignSelf: 'center',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		borderWidth: 1,
		borderColor: 'transparent',
		borderRadius: 16,
	},
	buttonSelectedAvatar: {
		zIndex: 2,
		top: 20,
		right: -60,
		height: 25,
		width: 25,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 25,
		borderWidth: 1,
		borderColor: colors.orange,
		backgroundColor: colors.white,
    },
    section: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
        gap: 20,
        marginTop: 200,
    },
    infoContainer: {
        display: "flex",
        marginVertical: 10,
        alignItems: "flex-start",
        justifyContent: "center",
        marginTop: 40,
    },
    info: {
        display: "flex",
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "center",
        gap: 10,
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: colors.black,
        marginTop: 10,
    },
    buttonContainer: {
        flex: 1,
        justifyContent: "center",
        gap: 10,
        marginTop: 20,
    },
    button: {
        fontFamily: 'Roboto-Regular',
        fontSize: 16,
        fontWeight: "400",
        lineHeight: 19,
        color: colors.white,
    }
});